### ISSUE TITLE
3494_黃元萱

### ISSUE THREAD

**Issue by hyxfish27** [ItsTiffanyChen/javascript-modularization#12]
Repo: [https://github.com/hyxfish27/webpack-modularization](https://github.com/hyxfish27/webpack-modularization)

#### loader
- [swc-loader](https://swc.rs/docs/usage/swc-loader)
類似 babel，但是速度較快，用來將較高版本的 Javascript 轉換成舊版瀏覽器相容的語法

#### plugin
- [CssMinimizerWebpackPlugin](https://webpack.js.org/plugins/css-minimizer-webpack-plugin/) 
能夠壓縮 CSS，並且優化 CSS 的打包流程
- [TerserWebpackPlugin](https://webpack.js.org/plugins/terser-webpack-plugin/)
webpack 的其中一種壓縮 js 的 plugin，能夠並行處理多個子任務，提高打包效率

**Comment by ItsTiffanyChen** [comment]
[這邊](https://github.com/hyxfish27/webpack-modularization/blob/main/webpack.config.js#L53) index.html 的 fileName 因為包含了 contenthash，會導致 devServer 無法抓預設的 index.html 為根目錄的入口（因為產出的 index.html 檔名不同了）
如果想要這樣做的話可能需要再看一下如何設定喔～
