### ISSUE TITLE
3166_翁郁婷

### ISSUE THREAD

**Issue by wengYuting** [ItsTiffanyChen/javascript-modularization#15]
## Repo
https://github.com/wengYuting/javascript-modularization-webpack

### Used loader: ts-loader
可使用 typescript 撰寫程式碼
https://webpack.js.org/guides/typescript/#loader

### Used plugin: ImageMinimizerWebpackPlugin
打包時自動壓縮圖檔
https://webpack.js.org/plugins/image-minimizer-webpack-plugin/

**Comment by ItsTiffanyChen** [comment]
thanks, owl!
