### ISSUE TITLE
2046_賴奕牧

### ISSUE THREAD

**Issue by 747adam** [ItsTiffanyChen/javascript-modularization#16]
2046_賴奕牧
repo: https://github.com/747adam/javascript-modularization

使用的 loader:
    1. sass-loader：載入 Sass/SCSS 文件並將其編譯為 CSS
    https://www.npmjs.com/package/sass-loader
    
使用的 plugin:
    1. ImageminWebpackPlugin：壓縮專案中的所有圖像
    https://www.npmjs.com/package/imagemin-webpack-plugin

**Comment by ItsTiffanyChen** [comment]
有怪獸就給讚！！
