### ISSUE TITLE
3318_林信錡

### ISSUE THREAD

**Issue by xinqilin** [ItsTiffanyChen/javascript-modularization#6]
repo:  &nbsp; [js-general-course](https://github.com/xinqilin/js-general-course)

 - 使用的 loader:
    * babel-loader:&nbsp;  ES6 或以上版本的 js 轉成 ES5
    
 - 使用的 plugin:
   * vanilla-tilt : &nbsp;  讓 dom 會動, 我需要這酷東西

**Comment by ItsTiffanyChen** [comment]
真是個莫名其妙的酷東西（？
